### ISSUE TITLE
Investigate if duplicate "Machine ID" values on nodes matter

### ISSUE THREAD

**Issue by jackfrancis** [jackfrancis/kamino#22]
The current implementation duplicates the Machine ID as new nodes consume the SIG-published image. We should investigate some more if this is a problem.

**Comment by Michael-Sinz** [comment]
While we have not noticed any problems due to Machine ID ending up duplicated due to VMSS-Prototype image clones, I have now included some code that will clean that up (or at least try to).

We do not consider it an error if it fails to do so but what we are doing should usually work very consistently.  (Have not noticed an failure in hundreds of test runs of that tooling...)

This just removes this one issue from being something we should be concerned about.

**Comment by Michael-Sinz** [comment]
Looks like this fix is not complete - the Machine ID does change but only once - something during deallocation of the VM seems to write a new value into it.

So, my testing needed to build not just one new VM but multiple new VMs to see that each of them is different and not just different than what was there before.
