### ISSUE TITLE
Add control plane taints in order to run on control plane VMs

### ISSUE THREAD

**Issue by jackfrancis** [jackfrancis/kamino#4]
We should prefer to schedule the vmss-prototype runtime on a control plane VM.

**Comment by Michael-Sinz** [comment]
Interesting question.  We could add a soft affinity to the control plane but in AKS (which we hope to support), that could not be possible since they are managed control plane.

What we have now is allow on masters and normal nodes with an option run force on masters.  Is that enough?   Or do we need to add a soft affinity to masters too?

**Comment by Michael-Sinz** [comment]
I claim this issue is closed since we have the scheduleOnControlPlane option.   Do we need anything else?
